# permissions for end users to view idaas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: idaas-viewer-role
rules:
- apiGroups:
  - idaas.idaas.io
  resources:
  - idaas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - idaas.idaas.io
  resources:
  - idaas/status
  verbs:
  - get
