# permissions for end users to edit idaas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: idaas-editor-role
rules:
- apiGroups:
  - idaas.idaas.io
  resources:
  - idaas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - idaas.idaas.io
  resources:
  - idaas/status
  verbs:
  - get
